# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DPJgxbKVbZ4mpkO3Qq1T2DxiytIL6J8p
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans , AgglomerativeClustering,DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score,davies_bouldin_score

iris=load_iris()
X=iris.data
# iris_df=pd.DataFrame(data=iris.data)
# print(iris_df.head())

scaler= StandardScaler()
X_scaled = scaler.fit_transform(X)

clustering_methods = ['K-means', 'Agglomerative Hierarchical Clustering', 'DBSCAN']
silhouette_scores = []
davies_bouldin_scores = []
num_clusters = [3, 3, None]

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans.fit(X_scaled)
kmeans_silhouette = silhouette_score(X_scaled, kmeans.labels_)
kmeans_davies_bouldin = davies_bouldin_score(X_scaled, kmeans.labels_)
silhouette_scores.append(kmeans_silhouette)
davies_bouldin_scores.append(kmeans_davies_bouldin)


agg_clustering = AgglomerativeClustering(n_clusters=3)
agg_clustering.fit(X_scaled)
agg_silhouette = silhouette_score(X_scaled, agg_clustering.labels_)
agg_davies_bouldin = davies_bouldin_score(X_scaled, agg_clustering.labels_)
silhouette_scores.append(agg_silhouette)
davies_bouldin_scores.append(agg_davies_bouldin)


dbscan = DBSCAN(eps=0.5, min_samples=5)
dbscan.fit(X_scaled)

if len(set(dbscan.labels_)) > 1:
    dbscan_silhouette = silhouette_score(X_scaled[dbscan.labels_ != -1], dbscan.labels_[dbscan.labels_ != -1])
    dbscan_davies_bouldin = davies_bouldin_score(X_scaled[dbscan.labels_ != -1], dbscan.labels_[dbscan.labels_ != -1])
    silhouette_scores.append(dbscan_silhouette)
    davies_bouldin_scores.append(dbscan_davies_bouldin)
else:
    silhouette_scores.append(None)
    davies_bouldin_scores.append(None)

results_df = pd.DataFrame({
    'Clustering Method': clustering_methods,
    'Number of Clusters': num_clusters,
    'Silhouette Score': silhouette_scores,
    'Davies-Bouldin Score': davies_bouldin_scores
})

print(results_df)